package com.tracabilite.tracabilite.web.common;

public class ApiMessage {
    public static final String INVALID_INPUT = "INVALID_INPUT";

    public static final String NOT_FOUND = "NOT_FOUND";

    public static final String SUCCESSFUL_OPERATION = "SUCCESSFUL_OPERATION";
    public static final String NO_DATA = "NO_DATA";
    public static final String OAUTH2SCHEMA = "oauth2schema";

    public static final String MATIERE_CREATED_SUCCESSFULLY = "MATIERE_CREATED_SUCCESSFULLY" ;
    public static final String MATIERE_UPDATED_SUCCESSFULLY = "MATIERE_UPDATED_SUCCESSFULLY";
    public static final String MATIERE_DELETED_SUCCESSFULLY = "MATIERE_DELETED_SUCCESSFULLY";
    public static final String MACHINE_UPDATED_SUCCESSFULLY = "MACHINE_UPDATED_SUCCESSFULLY";
    public static final String MACHINE_DELETED_SUCCESSFULLY = "MACHINE_DELETED_SUCCESSFULLY";
    public static final String MACHINE_CREATED_SUCCESSFULLY = "MACHINE_CREATED_SUCCESSFULLY" ;
    public static final String CLIENT_CREATED_SUCCESSFULLY = "CLIENT_CREATED_SUCCESSFULLY";
    public static final String BANDE_COMMANDE_CREATED_SUCCESSFULLY = "BANDE_COMMANDE_CREATED_SUCCESSFULLY";

    public static final String CLIENT_UPDATED_SUCCESSFULLY = "CLIENT_UPDATED_SUCCESSFULLY";
    public static final String BANDE_COMMANDE_UPDATED_SUCCESSFULLY = "BANDE_COMMANDE_UPDATED_SUCCESSFULLY";

    public static final String CLIENT_DELETED_SUCCESSFULLY = "CLIENT_DELETED_SUCCESSFULLY";
    public static final String BANDE_COMMANDE_DELETED_SUCCESSFULLY = "BANDE_COMMANDE_DELETED_SUCCESSFULLY";

    public static final String ARTICLE_DELETED_SUCCESSFULLY = "ARTICLE_DELETED_SUCCESSFULLY";
    public static final String BANDE_LIVRAISON_DELETED_SUCCESSFULLY = "BANDE_LIVRAISON_DELETED_SUCCESSFULLY";

    public static final String ARTICLE_UPDATED_SUCCESSFULLY = "ARTICLE_UPDATED_SUCCESSFULLY";
    public static final String BANDE_LIVRAISON_UPDATED_SUCCESSFULLY = "BANDE_LIVRAISON_UPDATED_SUCCESSFULLY";

    public static final String ARTICLE_CREATED_SUCCESSFULLY = "ARTICLE_CREATED_SUCCESSFULLY";
    public static final String BANDE_LIVRAISON_CREATED_SUCCESSFULLY = "BANDE_LIVRAISON_CREATED_SUCCESSFULLY";

    public static final String SERVER_ERROR_OCCURRED = "SERVER_ERROR_OCCURRED";

    public static final String ERROR_DELETE_CONTACT = "ERROR_DELETE_CONTACT" ;
    public static final String ERROR_LEVEL_MESSAGE = "ERROR_LEVEL_MESSAGE" ;
    public static final String MATIERE_ALREADY_EXIST = "MATIERE_ALREADY_EXIST" ;
    public static final String REQUIRED_VALIDATION_FAILED = "REQUIRED_VALIDATION_FAILED";
    public static final String MACHINE_ALREADY_EXIST = "MACHINE_ALREADY_EXIST";
    public static final String CLIENT_ALREADY_EXIST = "CLIENT_ALREADY_EXIST";
}
